### ISSUE TITLE
Usage with pyenv - is it even possible?

### ISSUE THREAD

**Issue by eugenweissbart** [matangover/mypy-vscode#10]
Greetings!

Ok, maybe I don't get something, but I've been trying to figure it out for myself and googling for some time with no luck.

So I have a macos system with mypy installed globally via brew. 
Then, I have pyenv-virtualenv installed. My project has its separate virtual environment where I install packages in.

Then, I create a new workspase in VSCode, select python interpreter for it located in pyenv's virtualenv. I install flask in the virtualenv and create a simple .py-file with flask import.

Although the interpreter can run the file, mypy plugin shows that there is no flask package installed.

How can I use selected interpreter for mypy in a workspace?

Thanks in advance!

**Comment by matangover** [comment]
Hi @eugenweissbart, it seems you did everything right, so I'm not sure what's the problem. In fact, Flask is [included in typeshed](https://github.com/python/typeshed/tree/master/third_party/2and3/flask), so mypy should always find it – even if it's not actually installed. You can try running mypy from the command-line on your module and add the `-v` option. That may help seeing why mypy cannot find the module, which is supposed to be in typeshed.

In my case the output shows that mypy can find the Flask stubs (even though I didn't install Flask!):
```
LOG:  Parsing .../mypy/lib/python3.8/site-packages/mypy/typeshed/third_party/2and3/flask/__init__.pyi (flask)
```

**Comment by matangover** [comment]
Please re-open if you can reproduce.
