### ISSUE TITLE
Pick up dmypy from venv

### ISSUE THREAD

**Issue by jorgen** [matangover/mypy-vscode#103]
My project has mypy as a dev dependency. I don't have mypy installed in my global environment, and when I load my project in VSCode I get the warning: ```The mypy daemon executable ('dmypy') was not found on your PATH. Please install mypy or adjust the mypy.dmypyExecutable setting.```

I can add the path to the dmypy that the project is configured for to settings.json and everything works, however I expect the dmypy executable to be first picked up from the "current selected interpreter", and if its not found there then fallback to the global fallback.

The problem with checking in the dmypy executable path in the repository is that there might not be a standard venv path (ie different python version strings etc.) and that Windows put the executables in the "venv/Scripts" folder while the POSIX platforms use "venv/bin" folder.

**Comment by matangover** [comment]
This option already exists, it's called `mypy.useActiveInterpreter`. Try it and let me know if it works for you.

**Comment by jorgen** [comment]
works like a charm! Thank you.
