### ISSUE TITLE
Unrecognized option: show_error_codes

### ISSUE THREAD

**Issue by gwenwahl** [matangover/mypy-vscode#12]
With a `mypy.ini` like:
```
[mypy]
...
show_error_codes = True
```
The extension says: 
Error reading mypy config file:
mypy.ini: [mypy]: Unrecognized option: show_error_codes = True

This is a valid option in the root `[mypy]` block according to https://mypy.readthedocs.io/en/stable/config_file.html#configuring-error-messages

**Comment by matangover** [comment]
Probably you have an older version of `mypy` installed. Please upgrade. See instructions:
https://github.com/matangover/mypy-vscode#updating

If you still have the same error, please post your mypyls & mypy versions.

**Comment by gwenwahl** [comment]
Ahh yup updating the language server fixed it. Thanks!
