### ISSUE TITLE
Allow for displaying only currently open files errors

### ISSUE THREAD

**Issue by evemorgen** [matangover/mypy-vscode#14]
Right now, when this extension is enabled it reports all mypy errors found in the workspace directory in the "problems" tab, which might lead to some anxiety in bigger projects. It would be nice to enable user to toggle between "all errors" and "errors in currently open files" (in a similar manner as Python extension is doing with linting errors). 

I'd be willing to help if pointed into the right direction how to implement such a thing if author was interested 😄

**Comment by matangover** [comment]
Hi Patryk, that's a good idea, I would definitely not want to cause any anxiety :) I think VS Code has this feature built in, have you tried using the Problems panel filter?

https://code.visualstudio.com/updates/v1_41#_problems-panel

**Comment by evemorgen** [comment]
Ah, I didn't know about the built-in feature in Problems panel filter, thanks!
