### ISSUE TITLE
No .py[i] files found

### ISSUE THREAD

**Issue by jeremygoh** [matangover/mypy-vscode#16]
I've followed the installation instructions for a mac but keep getting the error message saying

_"Error running mypy: There are no .py[i] files in directory"_

The default mypy linter in VSCode runs fine. Confirmed that running mypy in the directory on the terminal also works fine.

Is there anything additional that needs to be done e.g. configuring a venv or supplying additional arguments to ensure the extension picks up my files. I have a .mypy.ini file in the top level directory

**Comment by matangover** [comment]
Hi, sorry for the late reply :)

1) Do you have Python files in the root of the workspace folder (not in subfolders)? Mypy doesn't look in subfolders unless they contain an `__init__.py` file.

2) You said running mypy from the terminal works fine. Do you run mypy without any arguments, or do you provide a target folder?

3) If you want to set the target folder (or several target folders) for the mypy vscode extension, you can change the `mypy.targets` setting in VS Code settings.

**Comment by jeremygoh** [comment]
Thanks for the reply! 

Figured it out in the end that having a folder named types in the workspace was causing mypy to fail silently

**Comment by nup002** [comment]
In my case, the problem was caused by an incorrectly formatted `exclude` string in `mypy.ini`.

I had:
```
exclude = (?x)(
		  |/dist/*
		  |/ui_src/*
		  )
```
When it should have been
```
exclude = (?x)(
		  /dist/*
		  |/ui_src/*
		  )
```
Note the extra `|`  before `\dist\*`.

Mypy failed silently due to this hard to spot formatting error, and it took me quite a while to figure out where the problem lay.
