### ISSUE TITLE
Installation: Activate venv before install via pip

### ISSUE THREAD

**Issue by TimErdmann87** [matangover/mypy-vscode#18]
When installing on windows I needed to activate the venv before running the 'pip install ...' command. Otherwise, mypyls.exe plus additional files were not created.

On Windows:

$ python -m venv %USERPROFILE%\.mypyls
$ cd %USERPROFILE%\.mypyls\Scripts
$ .\activate
$ pip install "https://github.com/matangover/mypyls/archive/master.zip#egg=mypyls[default-mypy]"

**Comment by matangover** [comment]
Thanks for the heads up! I remember testing the installation instructions on Windows so that's a bit surprising:) Let me check again to see if I can reproduce.

**Comment by matangover** [comment]
The install instructions on the README work for me
