### ISSUE TITLE
Additional steps required to get working on Windows 10

### ISSUE THREAD

**Issue by reifnir** [matangover/mypy-vscode#2]
Creating a virtual Python environment on Windows creates a "Scripts" directory instead of "bin" and the subsequent build of mypyls creates an exe file.

The following undocumented steps were required so that the expected file (~/.mypyls/bin/mypyls) existed in order to get the extension working on Windows.

In cmd.exe, running as Administrator, run the following lines:
```
>mklink %userprofile%\.mypyls\bin %userprofile%\.mypyls\Scripts
symbolic link created for C:\Users\jandreasen\.mypyls\bin <<===>> C:\Users\jandreasen\.mypyls\Scripts

>mklink %userprofile%\.mypyls\Scripts\mypyls %userprofile%\.mypyls\Scripts\mypyls.exe
symbolic link created for C:\Users\jandreasen\.mypyls\Scripts\mypyls <<===>> C:\Users\jandreasen\.mypyls\Scripts\mypyls.exe
```

**Comment by matangover** [comment]
Thanks for the report! You can also change the `mypy.executable` setting in VS Code to `~/.mypyls/Scripts/mypyls.exe` instead of creating a symbolic link.

**Comment by kiwi0fruit** [comment]
WOW. Finally working mypy GUI for Windows. Two extension for PyCharm didn't work. VS Code default python extension was buggy. But it also needs some installation. For conda:

batch or git-bash:
```bash
conda create -n mypyls -c defaults -c conda-forge "python>=3.7" future mypy python-jsonrpc-server typed-ast mypy_extensions exec-wrappers
activate mypyls
pip install "https://github.com/matangover/mypyls/archive/master.zip#egg=mypyls[default-mypy]"
```
git-bash only:
```bash
exec=mypyls
execdir="$(dirname "$(type -p "$exec")")"
create-wrappers -t conda -b "$execdir" -f "$exec" -d "$(dirname "$execdir/wrap/$exec")" --conda-env-dir "$(dirname "$execdir")"
```
Then set mypy executable in VS Code to `<...>\Miniconda3\envs\mypyls\Scripts\wrap\mypyls.bat`

This may work without activation script wrapper but with this it's the safest way.

**Comment by matangover** [comment]
Finally managed to get a Windows machine to test the extension on! I added installation instructions for Windows and fixed the default path in the extension, so that the tricks offered here are not necessary anymore.

Windows users that install the latest version of the extension should have no problems.

By the way you can also upgrade the language server to mypyls 0.2 using the instructions here, to get the latest mypy version (0.740):
https://github.com/matangover/mypy-vscode#updating
