### ISSUE TITLE
Support relative path for mypy.executable

### ISSUE THREAD

**Issue by d-kimuson** [matangover/mypy-vscode#20]
Hello, thank you for your great work.

As the title suggests, I would like to request support for relative paths in `mypy.executable`.

## Background

The guide of this extension installs the mypy language server in the `~/.mypyls` virtual environment, but I'm going to install and use it directly in the project's virtual environment to make the version dependencies of the mypy and stub files the same as the project's environment.

If we want to apply a custom path, we can use `mypy.executable` as an absolute path, but since my project shares a workspace configuration with git, it would be preferable to be able to use a relative path from the workspace directory.

## Request

Is it possible to change to use relative path like `${workspaceFolder}/.venv/bin/mypyls` or `./.venv/bin/mypyls` in addition to an absolute path for resolving the path of `mypy.executable`?

Or is there another solution by existing features?

Thank you very much.

**Comment by matangover** [comment]
That's a great idea, I will accept a PR adding support for ${workspaceFolder} :)
It should be added here:
https://github.com/matangover/mypy-vscode/blob/f57df5b236166f59a72463d4f28806609a4dbb5d/src/extension.ts#L22
