### ISSUE TITLE
Couldn't launch mypy language server executable: TypeError: Cannot read property 'textDocumentSync' of null

### ISSUE THREAD

**Issue by AurimasNav** [matangover/mypy-vscode#21]
## Environment

**Python 3.9.0**

**VS Code**:
Version: 1.51.0-insider (system setup)
Commit: 2ee8b8c645ec8ab54304bacae7aa979c1d9c647a
Date: 2020-10-29T06:01:21.160Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

also tried **VS Code**:
Version: 1.50.1 (system setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Mypy 0.1.4**

## Description 
1. Installed mypy extension
![image](https://user-images.githubusercontent.com/7810047/97690000-0faf3a00-1aa5-11eb-8181-47257b4fd031.png)
2. Installed mypyls
![image](https://user-images.githubusercontent.com/7810047/97691216-bea04580-1aa6-11eb-8481-6b91f20e1590.png)
3. When launching VS Code getting the following errors:
![image](https://user-images.githubusercontent.com/7810047/97690277-703e7700-1aa5-11eb-85e6-fe811fbc14be.png)

## Output
```
2020-10-30 12:10:42,325 UTC - INFO - mypyls.python_ls - Starting PythonLanguageServer IO language server
2020-10-30 12:10:42,325 UTC - INFO - mypyls.python_ls - sys.executable = c:\users\user_name\.mypyls\scripts\python.exe
2020-10-30 12:10:42,325 UTC - INFO - mypyls.python_ls - sys.version = 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
2020-10-30 12:10:42,325 UTC - INFO - mypyls.python_ls - __file__ = c:\users\user_name\.mypyls\lib\site-packages\mypyls\python_ls.py
2020-10-30 12:10:42,334 UTC - ERROR - mypyls.python_ls - mypy is not installed. sys.path:
['C:\\Users\\user_name\\.mypyls\\Scripts', 'C:\\python39\\python39.zip', 'C:\\python39\\DLLs', 'C:\\python39\\lib', 'C:\\python39', 'c:\\users\\user_name\\.mypyls', 'c:\\users\\user_name\\.mypyls\\lib\\site-packages']
[Error - 12:10:42] Server initialization failed.
TypeError: Cannot read property 'textDocumentSync' of null
	at c:\Users\user_name\.vscode-insiders\extensions\matangover.mypy-0.1.4\node_modules\vscode-languageclient\lib\client.js:1972:47
```

**Comment by matangover** [comment]
Thanks for the report, let me look into this.

**Comment by matangover** [comment]
Ah, the problem seems to be that mypy was not installed in the mypyls venv. (This is because you installed mypyls from the zip file without specifying the default-mypy extra.)

To fix it just run:
```
c:\Users\user_name\.mypyls\bin\pip.exe install mypy
```
