### ISSUE TITLE
Publish on Open VSX

### ISSUE THREAD

**Issue by jnnkB** [matangover/mypy-vscode#26]
Hi! Could you please publish this extension on [Open VSX]( https://open-vsx.org.)? Its the Marketplace which is used by [VSCodium](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace). I would appreciate it very much. 

The instructions are available at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by matangover** [comment]
Yes, I can publish it. Can you test the beta version of the extension?
https://github.com/matangover/mypy-vscode/issues/27

**Comment by jnnkB** [comment]
If installed it and will report if find anything interesting. I just don't now how much time for coding python I will have in the next few weeks.

**Comment by matangover** [comment]
Done

**Comment by jnnkB** [comment]
Thanks a lot
