### ISSUE TITLE
Beta: mypy-vscode 0.2.0

### ISSUE THREAD

**Issue by matangover** [matangover/mypy-vscode#27]
Hi 🙂 
I made some major changes in the mypy-vscode extension. It would help if some people test it before I make the release. Please leave any feedback below, and note your OS / mypy version. Thanks!! 🚀 

To install this beta, [download the VSIX](https://github.com/matangover/mypy-vscode/releases/download/v0.2.0-beta/mypy-0.2.0.vsix) and install it in VS Code using the command `Extensions: Install from VSIX...`.

Here is the full change log:

- The extension no longer uses `mypyls` (the mypy language server). We now use the mypy daemon (`dmypy`) which is built into mypy. This leads to less maintenance burden, full mypy feature support, an easier installation.

- The `mypy.executable` setting is now deprecated (because it used to point to mypyls which is no longer used). Use the new `mypy.dmypyExecutable` instead (which points to dmypy). The extension will attempt to migrate your settings automatically if needed.

- Added support for multiple workspace folders. A separate mypy daemon will be launched for each workspace folder. All configuration settings can be set on a per-folder basis if desired.

- Added the option `mypy.runUsingActiveInterpreter` to run dmypy using the interpreter that is currently selected in the Python extension. Can be useful if you install a specific version of mypy in each project. However, normally this is not needed (your code is always checked against the active interpreter anyway).

- The extension no longer overrides mypy's `check_untyped_defs` setting to true. This means that code inside unannotated functions will no longer be checked by default. If you want the old behavior, create a `mypy.ini` file with the following contents:
  ```
  [mypy]
  check_untyped_defs=true
  ```

- Support the new interpreter storage in the Python extension (experimental replacement for the `python.pythonPath` setting).

- Support more mypy config file options, e.g. `files` and `strict` (in mypyls these options were not supported).

**Comment by seansnyder** [comment]
Hi @matangover! I've done some testing of this beta version in our environment. It seems to be working pretty well so far without any issues that seem like blockers.

There is one thing related to the default behavior for multiple workspace folders that is a little bothersome. I work with multiple top level folders in a workspace, some of which are not python repos and do not use mypy. The plugin seems to try to run mypy on all of them and pops up a little error in the bottom right every time vscode starts up for the folders without a mypy.ini file.

Perhaps it could skip running on workspace folders without a mypy.ini file by default? Or even just skip raising the error that triggers the little error popup.

<img width="471" alt="Screen Shot 2021-05-02 at 11 22 41 PM" src="https://user-images.githubusercontent.com/281501/116839184-49b9df80-ab9f-11eb-9a77-7c9f2b21b204.png">

```
[3] stderr:
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Cannot find config file 'mypy.ini'

[3] Error running mypy in /Users/ssnyder/projects/web: mypy failed with exit code 2. See Output panel for details
```

**Comment by matangover** [comment]
Thanks for testing! Indeed the extension runs mypy on each folder, but if there are no Python files in a folder the extension will normally not report an error. Did you explicitly change the mypy.configFile setting? Try clearing that setting, as it seems you are using the default value anyway. I think if you clear that setting (or set it only in the appropriate workspace folders where you want the extension to run), the error will go away. Please let me know if that helps. Thanks!

**Comment by seansnyder** [comment]
You're right, I did have that setting explicitly set. Removing it seems to have changed the behavior a little bit, though it is still raising error popups on startup. The error message has changed to this:

```
[3] stdout:
Daemon started

[3] stderr:
mypy-daemon: error: Missing target module, package, files, or command.

[3] Error running mypy in /Users/ssnyder/projects/web: mypy failed with exit code 2. See Output panel for details.
```

**Comment by seansnyder** [comment]
Thanks for the pointer. I removed that setting as well as a setting for explicitly setting the target files, and between the two the error popups on startup have gone away :)

**Comment by matangover** [comment]
I'm glad to hear that :)

**Comment by seansnyder** [comment]
btw I love this change. I greatly prefer being able to use the mypy package managed by the project's package manager and installed in the project's virtualenv, rather than a separate installation of mypy. In our case we use pipenv and specify the mypy dependency (and version) in our `Pipfile`. Now the mypy package used by VSCode will be certain to be the same one used on the command line locally + in CI, which we run via something like `pipenv run dmypy`.

**Comment by matangover** [comment]
Thanks, I'm happy to hear that. Do you use `mypy.runUsingActiveInterpreter`? I haven't tried it with Pipenv.

**Comment by seansnyder** [comment]
Yep, I'm using `mypy.runUsingActiveInterpreter` and it seems to be working as expected.

**Comment by walleXD** [comment]
@matangover I'm trying it out. Will report back soon

**Comment by matangover** [comment]
Thanks! 0.2.0 is now published, please report any issues you encounter.
