### ISSUE TITLE
How to handle venv installations in the workspace

### ISSUE THREAD

**Issue by WorldSEnder** [matangover/mypy-vscode#29]
In my setup, I have a virtual env inside the workspace, to handle my dependencies. Running the `dmypy` deamon fails (see further how to find out why it fails) with

    /path-to-project/env/lib/python3.9/site-packages is in the PYTHONPATH. Please change directory so it is not.

For clarity, my workspace setup:

    ┬─ path-to-project
    ├┬─ env / bin
    │├─ activate
    │└─ python
    ├─ foobar_module.py

Activating the env and running `mypy .` manually works.

In any case, the user experience is not great. What I did to find out what failed:

- Receive popup "Error running mypy in /home/martin/recreational/cql: mypy failed with exit code 2. See Output panel for details."
- Copy and manually execute command logged in the Output panel, which expectedly reproduces the failure
- Since no log output is generated, stop the daemon manually, then restart it with a log file:
   ```sh
   /home/martin/.cache/mypyls/bin/dmypy --status-file "/home/martin/.config/Code - OSS/"`
       `"User/workspaceStorage/37554b17b6b2153804b9b7f61a3ea1d5/matangover.mypy/"`
       `"dmypy-826702693d8cb430515d20b55351669920520582.json" run --log-file \
        "/home/martin/.config/Code - OSS/User/workspaceStorage/"`
        `"37554b17b6b2153804b9b7f61a3ea1d5/matangover.mypy/"`
        `"dmypy-826702693d8cb430515d20b55351669920520582.log" -- . \
        --show-column-numbers --no-error-summary --no-pretty --no-color-output \
        --python-executable /path-to-project/env/bin/python
   ```
  Note that it *appends* to the log file, so multiple invocations can give confusingly long log files, but I then discovered the error above.

My current workaround is overwriting `"mypy.targets": ["foobar_module.py"]` in the workspace config, but I believe this should just work (tm) with the default config.

---

I'm not sure what the correct way of calling dmypy is. Handling of python executables assumes everything is fine if no explicit one is given [here](https://github.com/python/mypy/blob/329e61507da2011b085738a825974433d09f0c6a/mypy/modulefinder.py#L725-L739). Running the mypy daemon in an activated environment, without an explicit `--python-executable` errors out while trying to check `site-packages`, which it shouldn't and could be assumed to be a bug in `dmypy`. Will update if I open a bug report there or find something related. Somehow running `mypy` manually does not.

Further investigation unearthed https://github.com/python/mypy/blob/329e61507da2011b085738a825974433d09f0c6a/mypy/find_sources.py#L20 which is called to expand filepaths to source files for `mypy`. Not sure if this could or should be replicated on `dmypy`.

---

Immediately actionable would be adding `--log-file` so I don't have to dig this up by hand next time.

**Comment by WorldSEnder** [comment]
Using version 0.2.0 from #27

**Comment by matangover** [comment]
First of all, thanks for trying the beta. Second, I can reproduce the issue with mypy 0.800. Please upgrade to mypy 0.812 to resolve the issue. It was a bug in mypy. Also the bad user experience (having to specify --log-file) is due to dmypy not handling the internal error correctly, so nothing I can do about that unfortunately.

If upgrading mypy doesn't resolve it, please let me know :)

By the way I never encountered this even using mypy 0.800, because I always use a leading dot in the name of my venv (e.g. `.venv`). In this case mypy ignores the folder.

P.S. another tip, in version 0.2 of the extension you don't need mypyls anymore, you can just install mypy normally on your system.

**Comment by WorldSEnder** [comment]
Thanks for the quick response, indeed upgrading to mypy 0.812 seems to resolve the issue. Props for trying older versions of mypy.

For the log file I thought adding a `--log-file` arguments when running `dmypy` from the extension could be beneficial, just didn't have the time to send a pull request. https://github.com/matangover/mypy-vscode/blob/2f2d0456a28f1641f63aa866322a924c380d5daf/src/extension.ts#L279-L281

I am already using `dmypy` only, but kept it in the old virtual env `~/.cache/mypyls/`, hence that naming confusion :)

**Comment by matangover** [comment]
Great, happy to know it's resolved
