### ISSUE TITLE
Python executable from venv is not used

### ISSUE THREAD

**Issue by alehed** [matangover/mypy-vscode#33]
For some reason the mypy extension doesn't recognize my python executable in a venv.

The log output shows

```text
Mypy extension activated, version 0.2.0
Registering listener for interpreter changed event
Waiting for Python extension to load
Python extension loaded
Listener registered
[1] Check workspace: ${workspaceFolder}
[1] Using config file: mypy.ini
[1] Received python path from Python extension: /usr/bin/python3
[1] Running dmypy in folder ${workspaceFolder}
${workspaceFolder}/env/bin/dmypy --status-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.json run --log-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --config-file mypy.ini --python-executable /usr/bin/python3
```

The `--python-executable /usr/bin/python3` is the problem here. It should be `${workspaceFolder}/env/bin/python`

The mypy settings are

```
{
    "mypy.configFile": "mypy.ini",
    "mypy.dmypyExecutable": "${workspaceFolder}/env/bin/dmypy",
    "mypy.targets": ["."]
}
```

Interestingly, the python extension outputs the following logs, showing that it runs pylance with the system python, but the linters with the venv one:

```
...
Python interpreter path: /usr/bin/python3
Starting Pylance language server.
> conda --version
Python interpreter path: ${workspaceFolder}/env/bin/python
... (invocations of flake8 and pycodestyle)
```

Unfortunately, it is not possible in vscode to specify the python path manually (for security reasons). Setting "run using active interpreter" tries to run everything using using the system python which is also not what I want.

**Comment by matangover** [comment]
This is unfortunately I think a symptom of a bug in Microsoft's Python extension, in the way it shares the interpreter path with other extensions. I reported it to the devs: https://github.com/microsoft/vscode-python/issues/15467.

If this is really the issue you are having, then it will only happen in the *first* invocation of mypy. After that, the interpreter path will be correct. Can you verify that? E.g. just save one of your files, and you shouldn't see the error anymore.

Can you reproduce this issue consistently? If yes can you give reproduction steps and note your OS and version of VS Code and the Python extension?

**Comment by alehed** [comment]
This is correct, after I save a file, the warnings disappear.

The output says:

```
Mypy extension activated, version 0.2.0
Registering listener for interpreter changed event
Waiting for Python extension to load
Python extension loaded
Listener registered
[1] Check workspace: ${workspaceFolder}
[1] Using config file: mypy.ini
[1] Received python path from Python extension: /usr/bin/python3
[1] Running dmypy in folder ${workspaceFolder}
${workspaceFolder}/env/bin/dmypy --status-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.json run --log-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --config-file mypy.ini --python-executable /usr/bin/python3
[1] Mypy output:
Daemon started
<Some import errors>

Document saved: ${workspaceFolder}/something.py
[2] Check workspace: ${workspaceFolder}
[2] Using config file: mypy.ini
[2] Received python path from Python extension: ${workspaceFolder}/env/bin/python
[2] Running dmypy in folder ${workspaceFolder}
${workspaceFolder}/env/bin/dmypy --status-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.json run --log-file /home/alex/.config/Code/User/workspaceStorage/c75fa14f80a26f7dcd6661af27693d09/matangover.mypy/dmypy-80690f3ce6c54e9de14878ef29f8a83a93369fd9.log -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --config-file mypy.ini --python-executable ${workspaceFolder}/env/bin/python
[2] Mypy output:
Restarting: configuration changed
Daemon stopped
Daemon started
```

I can reproduce this issue consistently.

I'm on Ubuntu 20.04 with vscode version:
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic
```

Python version 2021.5.842923320 and pylance version 2021.5.3.

The problem with reproducing it, I guess, is that the python version can only be set by clicking the interpreter version button which is entirely managed by the python extension and is not super reproducible (I use a workspace, so there it asks me to set it for the workspace or the folder, I think I set it for both, but there is no way to check what the current setting is...).

Is there any consequence in not setting the `--python-executable` command line option? One can even set it in the mypy.ini, if needed.

**Comment by dimaqq** [comment]
vscode recently started supporting `poetry` and perhaps Python interpreter selection was changed or improved?
this extension still doesn't find `dmypy` out of the box though :(

**Comment by matangover** [comment]
I will try to improve the workaround...

**Comment by matangover** [comment]
@dimaqq and @alehed could you please check the output of Microsoft's Python extension, to see if you have the 'DeprecatePythonPath' experiment active? It should show up as `User belongs to experiment group 'pythonDeprecatePythonPath'`. If indeed you have that experiment active, could you please opt out from that experiment by adding this to your settings:
```json
    "python.experiments.optOutFrom": [
        "pythonDeprecatePythonPath"
    ],
```
Then let me know if you can still reproduce the issue with the experiment disabled.

**Comment by matangover** [comment]
Also @dimaqq are you sure you're having the same problem as @alehed? Because you referred to "not finding `dmypy`" which is possibly a separate issue. Please explain your issue.

**Comment by matangover** [comment]
With the latest version of the Python extension (released 3 days ago by Microsoft) I can no longer repro this issue. Please let me know if you still can.

**Comment by alehed** [comment]
Since the last update I also can't reproduce the issue any more. I am not in the 'pythonDeprecatePythonPath' experiment group.

**Comment by matangover** [comment]
Great, @dimaqq how about you?

**Comment by dimaqq** [comment]
I'm a bit new to the whole `vscode` thing, so I'm a little confused at this point, TBH

**Comment by dimaqq** [comment]
My set up is that there's a Python project that uses `poetry` and its virtualenv has `mypy` installed. I have to manually "select interpreter" like "project-hash-py3.9: poetry" to get VSCode to recognise the libraries I import.

Even though this virtialenv has `mypy` and I can run `dmypy` from command line, VSCode (I assume this extension) keeps saying that:

`The mypy daemon executable ('dmypy') was not found on your PATH. Please install mypy or adjust the mypy.dmypyExecutable setting.`

I've disabled all experiments, and opted out from that specific one, and the error is still there. on every file save.

**Comment by matangover** [comment]
Ah, in that case I think you just want to enable the extension setting called "Run Using Active Interpreter":
![image](https://user-images.githubusercontent.com/5028956/122739373-952d6780-d28b-11eb-8493-766f075c0ddc.png)

**Comment by dimaqq** [comment]
orz   I was sure I had that toggled... but alas, no, it was off   orz
turning this on solved my problem, thank you!
