### ISSUE TITLE
mypy: error: unrecognized arguments

### ISSUE THREAD

**Issue by dahabakuk** [matangover/mypy-vscode#34]
im trying to migrate my workflow from sublime to vscode

after installing vscode i installed everything needed for python development which includes mypy extension (pip install mypy)

my client is win10 running python 3.6 (yes i know)
```
C:\Users\usr>python -V
Python 3.6.8
C:\Users\usr>pip list | findstr mypy
mypy                     0.670
mypy-extensions          0.4.1
```

which results in the following:
```

'C:\MyApps\WinPython64-3.6.8.0\python-3.6.8.amd64\Scripts\dmypy.EXE' --status-file 'c:\Users\usr\AppData\Roaming\Code\User\workspaceStorage\60e11f3a61c2fa7617972f971b4af50d\matangover.mypy\dmypy-40c3e3905ec527c809eaac3a66808ac5129ddbbc.json' run --log-file 'c:\Users\usr\AppData\Roaming\Code\User\workspaceStorage\60e11f3a61c2fa7617972f971b4af50d\matangover.mypy\dmypy-40c3e3905ec527c809eaac3a66808ac5129ddbbc.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable 'C:\MyApps\WinPython64-3.6.8.0\python-3.6.8.amd64\python.exe'
[1] stderr:
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: unrecognized arguments: --no-error-summary --no-pretty --no-color-output
```

im not sure if your extensions assumes a specific mypy version which has those parameters - or something else is missing here.

**Comment by matangover** [comment]
Which version of mypy do you have? Please install the latest version of
mypy, 0.812. That should fix the problem. Let me know if it works for you.

**Comment by dahabakuk** [comment]
yes u are correct - it seems my company proxy did intercept and/or provide old mypy files. trying with direct connect elsewhere seems to pull the latest mypy version and now this starts working.
thanks a lot!

**Comment by super9du** [comment]
I had upgrade mypy to the newest. But it still report this error. And then I check the setting "Mypy: Run Using Active Interpreter" of vscode , it works. Hope to help anyone.

check this option
![image](https://user-images.githubusercontent.com/38002762/160347081-acbb117e-3cf6-4c51-8a3b-90a993eefc7d.png)

**Comment by super9du** [comment]
> I had upgrade mypy to the newest. But it still report this error. And then I check the setting "Mypy: Run Using Active Interpreter" of vscode , it works. Hope to help anyone.
> 
> check this option ![image](https://user-images.githubusercontent.com/38002762/160347081-acbb117e-3cf6-4c51-8a3b-90a993eefc7d.png)

And I think it might be caused by not the latest version of dmypy.

**Comment by matangover** [comment]
You probably have several installations of mypy, and you only upgraded one of them but the one used by the extension is the old one. Please try to run `dmypy --version` in the terminal, what is the output? Note you can also change the setting `Mypy: Dmypy Executable` to the path of your liking, if dmypy is not on your system path.
