### ISSUE TITLE
Setting to add custom parameters on the command line

### ISSUE THREAD

**Issue by Morikko** [matangover/mypy-vscode#35]
I am working on a codebase with `follow_imports = silent` in `mypy.ini`. Unfortunately, this is not supported by the daemon and it crashes on start up with `dmypy: follow-imports=silent not supported`.

I would like to set custom parameters to overwrite the `mypy.ini` like `--follow-imports=normal`. It would then run: `dmypy run -- --follow-imports=normal` that works.

Is it something possible ?

**Comment by matangover** [comment]
I understand your use case. There's no setting to add command-line arguments, but I can suggest two workarounds:
1. Modify `mypy.ini`
2. Hack: Append your extra args to the `mypy.targets` setting

**Comment by Morikko** [comment]
1. Not possible because it is shared codebase (company owned)
2. That is working :tada: 

Thank you for the workaround :)

**Comment by DetachHead** [comment]
isn't this option supposed to allow you to pass custom args?

![image](https://user-images.githubusercontent.com/57028336/129115916-f659c527-451d-4c6f-bcdb-e83ecf1ca3da.png)

but as far as i can tell, this setting never gets read
