### ISSUE TITLE
mypy failed with error [Errno 61]Connection Refused

### ISSUE THREAD

**Issue by coneybeare** [matangover/mypy-vscode#37]
Is this a configuration, local setup, or extension error?

```
Mypy extension activated, version 0.2.0
Registering listener for interpreter changed event
Listener registered
[1] Check workspace: /Users/[redacted]/Code/[redacted]
[1] Received python path from Python extension: /Users/[redacted]/.pyenv/versions/3.9.5/envs/[redacted]-3.9.5/bin/python
[1] Running dmypy in folder /Users/[redacted]/Code/[redacted]
/Users/[redacted]/.pyenv/shims/dmypy --status-file '/Users/[redacted]/Library/Application Support/Code/User/workspaceStorage/a62c5d12881b39a8b8bff87622cc58aa/matangover.mypy/dmypy-2697fdea714588a4d127c15cd6828dc701243161.json' run --log-file '/Users/[redacted]/Library/Application Support/Code/User/workspaceStorage/a62c5d12881b39a8b8bff87622cc58aa/matangover.mypy/dmypy-2697fdea714588a4d127c15cd6828dc701243161.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /Users/[redacted]/.pyenv/versions/3.9.5/envs/[redacted]-3.9.5/bin/python
[1] stderr:
[Errno 61] Connection refused

[1] Error running mypy in /Users/[redacted]/Code/[redacted]: mypy failed with error: "[Errno 61] Connection refused". See Output panel for details.
```

**Comment by matangover** [comment]
I've never seen this error. It seems to be some mypy internal error. Could you attach the dmypy log file? It's the one specified in the dmypy command you sent, after --log-file

**Comment by coneybeare** [comment]
Could not reproduce after working around it for a few days, will close

**Comment by gwk** [comment]
FYI I see this error every once in a while, maybe once a week. Sometimes it persists across launches and I have to go into the `/[UUID]/matangover.py/` and delete the json file to get it working again.

**Comment by matangover** [comment]
Thanks for reporting it. This is probably not an issue with this extension, but an issue with dmypy itself. Probably the daemon is getting stuck and cannot communicate anymore. I'll reopen this issue for now anyway so we can investigate it.

When this error happens again, please do the following:

1. Post the mypy extension output (copy it from the VS Code Output panel).

2. Post the dmypy log file, which is created in the workspace storage. You can find the path to the log file in the dmypy command shown in the Output panel, e.g. `/path/to/dmypy [...]  --log-file '<log-file-path>'`

3. Try to reproduce the problem manually from the terminal by running dmypy -- copy the dmypy command from the Output panel and run it from inside the workspace folder

**Comment by pdpark** [comment]
Getting the same error after recent vscode upgrade. Tried running the `dmypy` command from the output panel in a terminal panel in vscode and got the same error - here's a redacted version of the cmd: 

`/Users/.../.local/bin/dmypy --status-file '/Users/.../Library/Application Support/Code/User/workspaceStorage/efd2...af08/matangover.mypy/dmypy-63c2...7f1a.json' run --log-file '/Users/.../Library/Application Support/Code/User/workspaceStorage/6efd...6af0/matangover.mypy/dmypy-aa7f...ec72.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /Users/.../.pyenv/versions/3.9.4/envs/dagster--dagster-3.9.4/bin/python`

**Comment by matangover** [comment]
Thanks for reporting.
1. Do you get this error consistently?
2. Can you paste the contents of the Mypy category in the VS Code Output panel?

The mypy extension gets the path to the Python executable from the VS Code Python extension. For some reason in your case this path is a non-existent pyenv folder. The error should probably go away after you select another Python interpreter using the command `Python: Select Interpreter`.

**Comment by gwk** [comment]
I often get this error if I reload the VS Code window (e.g. when you install an extension and it forces you to reload, or run `>Developer: Reload Window` from the command palette. It appears that the status file already exists, and so dmypy won't start. If I delete the status file shown in the extension startup console output, then reload window again, it seems to start working again (although to be honest I don't know if I'm leaking dmypy instances or something).

FWIW I have been wondering for some time if this extension could just put the status file in the workspace root, instead of burying it in `~/Library/Application Support/Code/User/workspaceStorage/...`. In my ideal world this would allow me to share the dmypy daemon between VS Code and command line usage, although whether that would actually be feasible I'm not sure. If you would like me to open a separate issue to discuss this idea, just let me know.

**Comment by gwk** [comment]
Here is an example log:
```
Mypy extension activated, version 0.2.1
Registering listener for interpreter changed event
Waiting for Python extension to load
Python extension loaded
Listener registered
[1] Check workspace: /Users/gwk/work/reflink
[1] Received python path from Python extension: /usr/local/bin/python3.10
[1] Running dmypy in folder /Users/gwk/work/reflink
/Library/Frameworks/Python.framework/Versions/3.10/bin/dmypy --status-file '/Users/gwk/Library/Application Support/Code/User/workspaceStorage/f3982104db452286ec0a5790c9a7e4b8/matangover.mypy/dmypy-b06a1b8d562f436d8b95d859f0e480037b5fb046.json' run --log-file '/Users/gwk/Library/Application Support/Code/User/workspaceStorage/f3982104db452286ec0a5790c9a7e4b8/matangover.mypy/dmypy-b06a1b8d562f436d8b95d859f0e480037b5fb046.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /usr/local/bin/python3.10
[1] stderr:
[Errno 61] Connection refused

[1] Error running mypy in /Users/gwk/work/reflink: mypy failed with error: "[Errno 61] Connection refused". See Output panel for details.
```

**Comment by matangover** [comment]
> I often get this error if I reload the VS Code window
Thanks a lot for the details. I'll try to reproduce it.

> FWIW I have been wondering for some time if this extension could just put the status file in the workspace root
Actually originally I put it there (that's the dmypy default), but I found it bothersome to add a file to the user's workspace folder -- then users might wonder why did a file appear out of nowhere and have to add it to their .gitignores. So I decided to hide it. If you want it would be pretty easy to add a configuration setting to make the status file be in the workspace root.

**Comment by YSaxon** [comment]
I'm getting the same sort of error, which I think started after upgrading ipykernel with `pip install -U ipykernel`

```
[1] Check workspace: /Users/ysaxon/[redacted]
[1] Received python path from Python extension: /Users/ysaxon/.pyenv/shims/python3
[1] Running dmypy in folder /Users/ysaxon/[redacted]
/Users/ysaxon/.pyenv/shims/dmypy --status-file '/Users/ysaxon/Library/Application Support/Code/User/workspaceStorage/01913170a88d38602656862aaefe36da/matangover.mypy/dmypy-001df27542bec1688c60e5af900d336a76adccc6.json' run --log-file '/Users/ysaxon/Library/Application Support/Code/User/workspaceStorage/01913170a88d38602656862aaefe36da/matangover.mypy/dmypy-001df27542bec1688c60e5af900d336a76adccc6.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable /Users/ysaxon/.pyenv/shims/python3
[1] stderr:
[Errno 61] Connection refused

[1] Error running mypy in /Users/ysaxon/[redacted]: mypy failed with error: "[Errno 61] Connection refused". See Output panel for details.
```

the log file has
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 221, in serve
    resp = self.run_command(command, data)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 264, in run_command
    return method(self, **data)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 323, in cmd_run
    return self.check(sources, is_tty, terminal_width)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 385, in check
    messages = self.fine_grained_increment_follow_imports(sources)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 559, in fine_grained_increment_follow_imports
    sources2 = self.direct_imports(module, graph)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 688, in direct_imports
    return [BuildSource(graph[dep].path, dep)
  File "/usr/local/Cellar/mypy/0.812/libexec/lib/python3.9/site-packages/mypy/dmypy_server.py", line 688, in <listcomp>
    return [BuildSource(graph[dep].path, dep)
KeyError: 'slack_bolt.response.response'
```

the `slack_bolt.response.response` in the last line appears to be referring to an object I imported from  [slack-bolt](https://pypi.org/project/slack-bolt/) with `from slack_bolt.response.response import BoltResponse`

I don't know what the odds are that this is actually a problem with mypy-vscode, versus with mypy itself or with the slack library, but I figured I'd post this in case A) it _is_ actually a problem with mypy-vscode, or B) it could be helpful for anybody else who comes to this page trying to debug a similar problem.

**Comment by YSaxon** [comment]
In any case the advice at https://github.com/matangover/mypy-vscode/issues/37#issuecomment-918150060, to delete the `'/Users/`[user]`/Library/Application Support/Code/User/workspaceStorage/`[UUID]`/matangover.mypy/dmypy-`[UUID]`.json'` file, appears to have worked

**Comment by matangover** [comment]
I've released a new version which fixes the bug. If for any reason you still encounter this error please enable the `mypy.debugLogging` option and attach the log.

**Comment by gwk-treeline** [comment]
Would you mind linking to the fix commit/PR? I’m curious.
