### ISSUE TITLE
int & float seem interchangeable

### ISSUE THREAD

**Issue by bozdoz** [matangover/mypy-vscode#4]
Hello!

Great plugin!  I've just been playing around with it, and realized that it doesn't seem to realize when an int is passed instead of a float:

No problem:
```python
def add(a: int, b: int) -> float:
    return a + b
```

However it **does** identify **problems** when a float is passed instead of an int:

```python
def add(a: float, b: float) -> int:
    return a + b
```

Not sure if this is just part of python's typing or not.  Thought I'd ask about it.  Thanks!

**Comment by matangover** [comment]
This is expected – not related to the plugin itself, but to the behavior of mypy itself. An `int` is considered to be compatible with `float`. See mypy documentation: [duck type compatibility](https://mypy.readthedocs.io/en/latest/duck_type_compatibility.html).
