### ISSUE TITLE
Add a setting to disable extension in one folder (for multi-root workspaces)

### ISSUE THREAD

**Issue by bagage** [matangover/mypy-vscode#41]
When working in a multi-root workspace, with some workspace not using mypy, you cannot disable it. You either end up with a lot of errors because mypy is checking it and a lot of resources used to check all files, or you have to disable it completely.

It would be very convenient to have a `mypy.enabled` settings, so that we can choose per folder if mypy needs to run or not.

**Comment by matangover** [comment]
Nice request, I'd accept a PR implementing it if you're up for it. As a workaround for now you can change the `mypy.targets` setting to `/dev/null` (or equivalent for Windows).

![image](https://user-images.githubusercontent.com/5028956/138535152-0add74bd-c969-490b-b7f0-b868ac1d4fc0.png)

**Comment by bagage** [comment]
Update: I'm sorry @matangover but I must admit that I won't have the time to properly do it, so if anyone's willing to do it feel free, I'll use the workaround for now. Thanks for your work!

**Comment by matangover** [comment]
No problem :)

**Comment by matangover** [comment]
Fixed in 0.2.3
