### ISSUE TITLE
Support to use subdirectory as root directory for mypy

### ISSUE THREAD

**Issue by aleksanb** [matangover/mypy-vscode#49]
Hello.

Great work on developing this plugin, it really just works <3.
I have a question: our project has a structure like

```
backend
>app
>>hyre
>>>actual.py
>>>python.py
>>>files.py
>>mypy.ini
>othersubdirectories
```

I'd like to be able to open the root directory, `backend` in vscode to be able to see all files in the repo, but because we use a plugin to mypy, django-mypy, that uses the following key in mypy.ini to specify the location of django settings, we have to use `app` as the root dir in vscode instead.

<img width="441" alt="bilde" src="https://user-images.githubusercontent.com/1413365/155317492-06cca5ba-af6d-4191-825e-753ac899a082.png">

This is because if `myproject` is the vscode root, then  the imports of hyre.settings fails, as no module named `hyre` is (rightly) accessible from the root.

So my suggestion for a solution would be:
Could we add a setting key to specify what folder to run dmypy from?

**Comment by matangover** [comment]
Hi, thanks for your suggestion! What happens if you set `django_settings_module = backend.hyre.settings`?

**Comment by aleksanb** [comment]
> Hi, thanks for your suggestion! What happens if you set `django_settings_module = backend.hyre.settings`?

This might work. I'll test it. The weirdest thing then is that the .ini file has to know about the folder structure it's contained in further out

**Comment by matangover** [comment]
Right, because the thing is that it's not really the ini file that has to know about it, it's the "mypy django" plugin, which is imported by mypy, which tries to import your settings module. (I'm just guessing... because I've never used this plugin)

**Comment by aleksanb** [comment]
Yeah, that seems correct.

**Comment by aleksanb** [comment]
There is a concept of PYTHONPATH="app" that's already used by VSCode, perhaps respecting that variable would solve things.

**Comment by matangover** [comment]
Mypy has the `mypy_path` config option for adding directories to the module search path. This setting seems to by the way [also be respected](https://github.com/typeddjango/django-stubs/issues/224) by the `mypy_django` plugin. Does this solve your issue?
