### ISSUE TITLE
Installation instructions broken on OSX

### ISSUE THREAD

**Issue by reverie** [matangover/mypy-vscode#5]
`python -m venv ~/.mypyls` works fine, but the resulting `bin` directory doesn't have a `pip` executable. It only has `python` and `python3`. So the next line of instructions (`~/.mypyls/bin/pip install "https://github.com/...."`) fails with a "No such file or directory" error

**Comment by matangover** [comment]
Seems you have an old version of Python that doesn't include pip. Try installing pip according to the instructions: https://pip.pypa.io/en/stable/installing/

**Comment by reverie** [comment]
@matangover No, I have pip installed

**Comment by matangover** [comment]
Which Python version are you using? Since 3.4 `venv` is supposed to install `pip` in the virtual environment by default.

**Comment by matangover** [comment]
>>> @matangover No, I have pip installed

Does the file ~/.mypyls/bin/pip exist? If not, you do not have pip installed inside the virtual environment ~/.mypyls

**Comment by reverie** [comment]
My bad, thank you!
