### ISSUE TITLE
Works only with "using active interpreter" - duplicate

### ISSUE THREAD

**Issue by pitris90** [matangover/mypy-vscode#52]
I couldn't reopen my issue (probably because you closed it), so I have to open new one.

Ok, so now it works in my workspace with python files, but not in workspace with jupyter notebooks that are using python inside... Error code seems to be same as before in workspace with python files, where it works now. Here is full output from that mypy extension: 
Mypy extension activated, version 0.2.2
Registering listener for interpreter changed event
Waiting for Python extension to load
Python extension loaded
Listener registered
[1] Check workspace: c:\Users\pitris90\Documents\ib031
Activation complete
[1] Received python path from Python extension: C:\Users\pitris90\AppData\Local\Programs\Python\Python39\python.exe
[1] Running dmypy in folder c:\Users\pitris90\Documents\ib031
'C:\Users\pitris90\AppData\Local\Programs\Python\Python39\Scripts\dmypy.EXE' --status-file 'c:\Users\pitris90\AppData\Roaming\Code\User\workspaceStorage\c4a6a906c53a6dc6bfa88936257de3da\matangover.mypy\dmypy-c6c45c66c8becc35250f3318cfdc10b131bc9d78-4184.json' run --log-file 'c:\Users\pitris90\AppData\Roaming\Code\User\workspaceStorage\c4a6a906c53a6dc6bfa88936257de3da\matangover.mypy\dmypy-c6c45c66c8becc35250f3318cfdc10b131bc9d78.log' -- . --show-column-numbers --no-error-summary --no-pretty --no-color-output --python-executable 'C:\Users\pitris90\AppData\Local\Programs\Python\Python39\python.exe'
[1] Error running mypy in c:\Users\pitris90\Documents\ib031: mypy failed with exit code 3221225477. See Output panel for details.

_Originally posted by @pitris90 in https://github.com/matangover/mypy-vscode/issues/51#issuecomment-1080573955_

**Comment by matangover** [comment]
Whoops, weird that you can't reopen it.. sorry about that, I reopened the original issue, please post it there
