### ISSUE TITLE
Can't --ignore-missing-imports

### ISSUE THREAD

**Issue by q00u** [matangover/mypy-vscode#6]
`--ignore-missing-imports` is in the list of Mypy Args, but I'm still seeing for example: "No library stub file for module 'numpy'"

Mypy 0.1.3
Python 3.7.3
VSCode 1.39.1

(Code runs fine, it's just the unnecessary Problems are annoying)

**Comment by matangover** [comment]
It took me some time to understand, but now I got it. The 'Mypy Args' setting that you were referring to is used only by Microsoft's Python Extension. My extension does not use this setting at all – it uses the mypy.ini config file instead, which is more flexible.

Please create a mypy.ini config file in your workspace folder, with the following content:

```ini
[mypy]
ignore_missing_imports = True
```

After creating this file, you should restart VS Code and the changes will be applied.

Please reopen if this doesn't solve your issue :)
