### ISSUE TITLE
separate isolated diagnostics in 1 workspace

### ISSUE THREAD

**Issue by beauxq** [matangover/mypy-vscode#62]
I have different folders in the workspace that contain the same script name,
```
workspace
|- program-a
|  \- main.py
\- program-b
   \- main.py
```
I would like to receive separate isolated diagnostics for these separate folders, so that it doesn't care that the same name is in two different places. Is there a way I can do that?

The diagnostics say
> error: Duplicate module named "main" (also at "program-a/main.py")

------

The readme has this:
> Supports multi-root workspaces: will launch a separate mypy daemon for each workspace folder.

I'm not sure whether I understand it correctly. I thought it would be the solution to this problem.

I tried putting the separate folders in the `targets` setting.

![Screenshot from 2022-09-20 08-12-01](https://user-images.githubusercontent.com/6052147/191299856-bfadd903-f14a-4d8e-b0d2-d600559f9fc5.png)

**Comment by matangover** [comment]
Seems like you are not actually using a multi-root workspace. You can create a multi-root workspace by first opening the "program-a" folder only, then running command "Add Folder to Workspace", and choosing "program-b". Does this solve your problem?

**Comment by matangover** [comment]
In general another easier way to solve it is to add an `__init__.py` file next to each `main.py` (although you might need to rename `program-a` to `program_a` so that it's a valid python module name).

**Comment by beauxq** [comment]
> Seems like you are not actually using a multi-root workspace. You can create a multi-root workspace by first opening the "program-a" folder only, then running command "Add Folder to Workspace", and choosing "program-b". Does this solve your problem?

Yes. I didn't understand how to make a multi-root workspace. Thanks.

> In general another easier way to solve it is to add an `__init__.py` file next to each `main.py` (although you might need to rename `program-a` to `program_a` so that it's a valid python module name).

This is specifically the reason I put the hyphen in `program-a` - because I want to make sure it is _NOT_ seen as a module.
