### ISSUE TITLE
[feature request] config in vscode settings for sync

### ISSUE THREAD

**Issue by beauxq** [matangover/mypy-vscode#63]
For a global mypy config, I put a config file in my home folder (`~/.config/mypy/config`). But that means I have to maintain that config file on every machine that I work on.

I would like a configuration that works with vscode settings sync, so if I change my mypy config on one machine, it automatically changes on others.

**Comment by matangover** [comment]
Would https://github.com/matangover/mypy-vscode/issues/35 solve your needs?

**Comment by beauxq** [comment]
> Would #35 solve your needs?

I think it would ff the setting is in vscode settings, so that it works with vscode settings sync.

I'm not sure what settings are available in a config file and not with command line arguments, and vice versa, but that would be more of a problem with mypy, rather than with your extension.

**Comment by matangover** [comment]
OK, so closing in favor of #35
