### ISSUE TITLE
In a multi-root workspace, excluded files from the .vscode config are not honored

### ISSUE THREAD

**Issue by mver-al** [matangover/mypy-vscode#75]
When you have a multi-root workspace, with child directory b below a both defined as roots, and you exclude directory b from the vscode config in its parent (`files.exclude`), the extension runs mypy for both folders, while the exclude setting is not honored. So directory b is also checked as part of the run from its parent a.

This results into problems where mypy from a different venv is used or the configuration differs. I'm not sure if this is intended behavior? As a workaround I can use the `mypy.targets` setting to get the desired behavior.

**Comment by matangover** [comment]
Thanks for the report. Yes, this is intended. This extension intentionally doesn't honor the `files.exclude` setting. If you want to exclude files you can use the `mypy.targets` setting as you said or Mypy's [exclude config](https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude).
