### ISSUE TITLE
How to debug `mypy-vscode`

### ISSUE THREAD

**Issue by mflova** [matangover/mypy-vscode#76]
I am using the following configuration:

```
    "mypy.runUsingActiveInterpreter": true,
    "python.linting.mypyEnabled": true,
    "python.linting.mypyArgs": [
        "--ignore-missing-imports",
        "--follow-imports=silent",
        "--show-column-numbers",
        "--strict"
    ],
```

I am using virtual environment managed by poetry and the active interpreter in my vscode is set to be the one that has `mypy` installed in the environment (the one created by poetry). If I disable the extension, I can see that VSCode already reports the problem, although it takes around 6s to see the output after saving a single file in a large codebase, meaning that `mypy` is properly detected within the interpreter.

When I set up the `dmypy` server in the terminal + with virtual environment activated, everything is as expected: `dmypy run` starts the server, and with `dmypy check` or `dmypy recheck` I can scan the issue I commented above in less than 1 second after being saved.

However, for this extension is hard to see what's happening. I would expected to be as quick as the terminal version with `daemon` server tool, but it is not the case. It takes same time as if I had the server not running. I checked with `dmypy status` within the terminal and with the corresponding interpreter active, and it says there is no `daemon` server running. The only argument I added is `mypy.runUsingActiveInterpreter`, which should be the only one I need to set up in order to use in the python interpreter where `mypy` lies.

Is there a way I can see the commands or the logs from this addon? I have no idea where I can search for the failing part.

**Comment by matangover** [comment]
Open the VSCode `Output` view and select the `Mypy` output channel. There you can see all the commands executed by the extension and their full output. If you need additional debug logging, you can enable the "Debug Logging" setting.
<img width="772" alt="image" src="https://github.com/matangover/mypy-vscode/assets/5028956/49a5ea8f-fb0d-49ba-85b8-633a419be61b">

**Comment by matangover** [comment]
Closing due to lack of response, please reopen if needed
