### ISSUE TITLE
Manual Download Needed

### ISSUE THREAD

**Issue by Mjvolk3** [matangover/mypy-vscode#77]
Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by matangover** [comment]
What do you mean?

**Comment by matangover** [comment]
Closing due to no response, please reopen if needed
