### ISSUE TITLE
[help or feature request] How to pass in "--explicit-package-bases" argument ?

### ISSUE THREAD

**Issue by JDurSyn** [matangover/mypy-vscode#78]
As in title,

Mypy just does not run on my repo otherwise

Many thanks in advance !

**Comment by matangover** [comment]
Hi, you have two options currently:

1. Add a mypy.ini file which sets this argument
2. Add this argument in the targets - workaround as described here: https://github.com/matangover/mypy-vscode/issues/35#issuecomment-887893484

**Comment by matangover** [comment]
Closing this as duplicate of #35
