### ISSUE TITLE
Unable to deploy resources using ARM template

### ISSUE THREAD

**Issue by ikky709** [matangover/mypy-vscode#80]
Unable to deploy resources, using the correct checkout version "actions/checkout@v4"  and i keep getting the same error.

Run Azure/arm-deploy@v1
Changing subscription context...
Validating template...
Warning: ERROR: [Errno 2] No such file or directory: './Arm-Templates/Resourcegroup.Json'

Warning: Template validation failed.
Creating deployment...
Error: ERROR: [Errno 2] No such file or directory: './Arm-Templates/Resourcegroup.Json'

Error: Deployment failed.

**Comment by matangover** [comment]
I have no idea what you're talking about, probably posted it in the wrong repository
