### ISSUE TITLE
What to do when plugin can't kill dmypy

### ISSUE THREAD

**Issue by MakonnenMak** [matangover/mypy-vscode#90]
Specifically when we hit this line here

https://github.com/matangover/mypy-vscode/blob/d644253d21551c05d229b5d8b21680a453bf84da/src/extension.ts#L173C1-L174C1

Is there a mechanism to manually kill it ?

**Comment by matangover** [comment]
Hi, I missed your post - sorry! Are you able to reproduce this problem? Does it happen often?

**Comment by matangover** [comment]
Closing because I can't reproduce this issue. Please re-open if you have more details.
