### ISSUE TITLE
Feature request: run mypy on the contents of a jupyter notebook

### ISSUE THREAD

**Issue by arikrundquist** [matangover/mypy-vscode#94]
This extension is probably the only reason I enjoy developing in python. I rely heavily on static type checking to both guide and sanity-check myself as I write code, and the fact that this extension gives immediate feedback each time I save lets me get the feedback I need without having to break out of my code-writing flow to run mypy manually over my workspace.

The only thing this extension lacks is support for jupyter notebooks. I'll be honest, I hardly ever use notebooks, but this week I was thinking about making one and discovered that I no longer got automatic type checking. As much as I was wanting to use a notebook in this particular instance, I will almost certainly resort to just using a regular python file because I cannot stand writing python without getting automatic feedback about my type safety... it's too bad though, I know notebooks are extremely popular in some circles and it's a shame that notebooks don't have access to this feature that I've come to rely so much on. Would it be possible to extend the extension to support `.ipynb` notebooks?

Here is a snippet that is clearly incorrect taken from a regular `.py` file:
![image](https://github.com/matangover/mypy-vscode/assets/22827799/597f1c37-5c36-4562-8561-f3ae7411487d)

When placed in a notebook, the same snippet does not report an error, so I can easily write code that fails at run-time:
![image](https://github.com/matangover/mypy-vscode/assets/22827799/d1c2c92c-7039-469b-b7b8-70bde163bb1b)

Poking around the internet, I found the `mypy-ipython` module which does do some type checking, but it will only type check cells that have already been run, and it must manually be invoked by running a cell containing `%mypy`.

I think it should be possible to get this extension to work in a notebook context, since I also noticed that pylance and ruff continue to report some issues:
![image](https://github.com/matangover/mypy-vscode/assets/22827799/e8661ffb-5554-4364-ac42-18130e3b6cbf)

**Comment by matangover** [comment]
This is released in 0.4.0, I hope it helps. In general Pylance has better support for notebooks, but it can be useful at times to run mypy too.
